name: CICD

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check listar
      run: ls
    - name: docker build
      run: |
        cd vote
        docker build -t roxsross12/vote-app:1.0.0 .
    - name: docker images
      run: docker images
